// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <header className="w-full h-20 border flex justify-center	items-center mb-4">Header</header>
//         <div className="w-full flex space-x-4 ">
//       <aside className="w-1/4	h-80 border	">side menu</aside>
//       <main className="w-3/4 h-80 border	">{children}</main>
//       </div>
//       <footer className="w-full h-20 border flex justify-center	items-center mt-4">Footer</footer>

//       </body>
//     </html>
//   );
// }


import HeaderComp from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PauseOnHover from "@/components/slider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">
       <div className="grid md:grid-cols-3 gap-4">
        <header className="col-span-3 bg-green-500"> <HeaderComp/> </header>
        <aside className="col-span-3 md:col-span-1 bg-orange-400 ">side bar</aside>
        <main className="col-span-3 md:col-span-2 bg-gray-500">{children}</main>
        <footer className="col-span-3 bg-sky-300 m-8"> <PauseOnHover /> </footer>

       </div>
       </div>
      </body>
    </html>
  );
}

